config/routes.rb
Rails.application.routes.draw do
  resources :packing_lanes do
    resources :packing_lane_boxes, only: %i[show edit update], shallow: true do
      member do
        post 'create_stock'
        post 'move_diff_from_stock'
        post 'move_to_stock'
        get 'packing_list'
      end
    end
  end
  resources :participants do
    resources :group_changes, shallow: true, except: %i[index show]
  end
  resources :diets
  resources :orders do
    member do
      post 'order'
      post 'deliver'
      post 'store'
      post 'cancel'
    end
    resources :order_articles, only: %i[create destroy], shallow: true
    get 'edit_quantities', on: :member
  end
  resources :boxes do
    resources :group_boxes, path: 'groups', as: :group, only: [:show] do
      resources :extra_ingredients, only: %i[new create edit update destroy], shallow: true
      resources :group_box_ingredients, path: 'ingredients', as: :ingredient, only: [:show]
    end
    member do
      get 'packing_lists_groups'
      get 'packing_lists_articles'
      get 'ingredient_meals'
      get 'packing_lists_missing_ingredients'
      get 'packing_lists_lanes'
      get 'all_packing_lists'
    end
  end
  resources :groups do
    resources :group_meal_participations, shallow: true, except: :show, path: 'meal_participations'
    get 'meals_overview', on: :collection
    get 'diets_overview', on: :collection
    resources :meal_selections, only: %i[index create destroy], shallow: true
  end
  devise_for :users
  resources :suppliers
  resources :articles do
    resources :hoards, shallow: true, except: %i[index show]
    resources :stock_changes, only: %i[index]
    get :laga, on: :collection
    post :update_stock, on: :member
    get :inventory_list, on: :collection
  end
  root 'dashboards#show'
  resource :dashboard do
    get 'groups_missing_packing_lane'
    get 'ingredients_missing_article'
    get 'ingredients_without_box'
    get 'recipes_without_content'
    get 'missing_ingredients'
    get 'upcoming_boxes'
    get 'upcoming_order_requirements'
    get 'upcoming_orders'
  end
  resources :meals
  resources :ingredients do
    get 'all', on: :collection
    get 'with_missing_alternatives', on: :collection
    resources :ingredient_alternatives, shallow: true, except: %i[index show]
  end
  resources :recipes do
    get 'kochbuch', on: :collection
  end
  resources :calculations, only: :update
  namespace :import do
    root 'imports#show'
    resource :articles, only: :create
    resource :ingredients, only: :create
    resource :participants, only: :create
    resource :groups, only: :create
    resource :diets_ingredients, only: :create
    resource :extra_ingredients, only: :create
  end
  resources :users, except: :show
  resources :units, only: %i[index new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  include NormalizedQuantityUnit

  enum :packing_type, { bulk: 0, piece: 1 }

  belongs_to :supplier
  belongs_to :ingredient
  has_many :group_box_articles
  has_many :boxes, -> { distinct }, through: :group_box_articles
  has_many :article_box_order_requirements
  has_many :order_articles, dependent: :restrict_with_error
  has_many :packing_lane_article_stocks, dependent: :delete_all
  has_many :active_packing_lane_article_stocks, -> { where(box: Box.picked) }, class_name: 'PackingLaneArticleStock'
  has_many :hoards
  has_many :stock_changes, -> { order(created_at: :desc) }, dependent: :destroy

  validates :stock, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than: 0 }
  validates :needs_cooling, inclusion: { in: [true, false] }
  validates :packing_type, presence: true
  validates :nr, uniqueness: true, if: -> { nr.present? }

  validates :quantity, numericality: { equal_to: 1, message: 'muss bei Schüttgut auf 1 gesetzt sein' }, if: :bulk?
  validates :unit, inclusion: { in: %w[g], message: 'erlaubt nur g bei Schüttgut' }, if: :bulk?

  default_scope { order(priority: :asc, quantity: :desc) }

  scope :lexical, -> { joins(:ingredient).reorder('ingredients.commodity_group', 'ingredients.name', 'priority') }

  delegate :on_demand?, to: :ingredient

  def to_s
    nr_str = nr.nil? ? '' : "##{nr} "
    name_str = name.blank? ? '' : "\"#{name}\" "
    "#{nr_str}#{name_str}#{quantity_unit.humanize} #{ingredient}"
  end

  def full_name
    "#{self} von #{supplier}"
  end

  def ordering_name
    article_name = name && name.present? ? " - #{name}" : ''
    "#{ingredient.name}#{article_name}"
  end

  def packing_name
    "#{ingredient.name} - #{packing_subheading}"
  end

  def packing_subheading
    parts = [supplier.name]
    parts << name if name.present?
    parts << quantity_unit.humanize if packing_type == 'piece'
    parts.join(' - ')
  end

  def base_price
    return nil unless price && quantity && unit

    (price / quantity.to_d * (%w[g ml].include?(unit) ? 1000 : 1)).round(2)
  end

  def ingredient_unit
    IngredientUnit.new(ingredient_id, unit)
  end

  def sums_by_box
    @sums_by_box ||= group_box_articles.group(:box_id).sum(:quantity)
  end

  def order_requirements
    @order_requirements ||= article_box_order_requirements.index_by { |abor| abor.box_id }
  end

  def order_requirement_of(box)
    order_requirements.fetch(box.id, NoOrderRequirement.new)
  end

  def current_order_limit
    return nil if order_limit.nil? # unlimited

    [0, order_limit - quantity_ordered - quantity_delivered].max
  end

  def quantity_ordered
    order_articles.joins(:order).merge(Order.ordered).sum(&:quantity_ordered)
  end

  def quantity_delivered
    order_articles.joins(:order).merge(Order.delivered_or_stored).sum(&:quantity_delivered)
  end

  def quantity_unit_stock
    quantity_unit * stock
  end

  def packing_lane_stock
    active_packing_lane_article_stocks.sum(&:quantity)
  end

  def quantity_unit_packing_lane_stock
    quantity_unit * packing_lane_stock
  end

  def surplus
    stock + packing_lane_stock - article_box_order_requirements.sum(&:stock)
  end

  def quantity_unit_surplus
    quantity_unit * surplus
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  authorize_resource
  before_action :set_article, only: %i[show edit update destroy update_stock]

  def index
    @articles =
      Article
      .includes(:supplier, :ingredient, :active_packing_lane_article_stocks, :article_box_order_requirements)
      .joins(:ingredient).lexical
    @order_counts = OrderArticle.all.group(:article_id).count
  end

  def laga
    @articles = Article.includes(:supplier, :ingredient).joins(:ingredient).lexical
    @articles = filter(@articles)
  end

  def show; end

  def new
    @article = Article.new(params.permit(:supplier_id, :ingredient_id))
  end

  def edit; end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Artikel wurde erfolgreich erstellt.' }
      else
        format.html { render :new, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Artikel wurde erfolgreich aktualisiert.' }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @article.destroy
        format.html { redirect_to articles_url, notice: 'Artikel wurde erfolgreich gelöscht.', status: :see_other }
      else
        format.html do
          redirect_to @article, status: :see_other, alert: @article.errors.full_messages
        end
      end
    end
  end

  def update_stock
    @article_stock_action = ArticleStockAction.new(
      article: @article,
      user: current_user,
      **params.expect(article_stock_action: [:action])
    )
    @article_stock_action.call if @article_stock_action.valid?
  end

  def inventory_list
    render_pdf InventoryList.new
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.expect(
      article: %i[ingredient_id supplier_id price quantity unit notes name
                  order_limit priority needs_cooling packing_type nr]
    )
  end

  def filter(articles)
    filter_search(filter_cooling(articles))
  end

  def filter_cooling(articles)
    return articles unless params[:cooling]

    case params[:cooling]
    when 'warm' then articles.where(needs_cooling: false)
    when 'cold' then articles.where(needs_cooling: true)
    else articles
    end
  end

  def filter_search(articles)
    return articles unless params[:search]

    articles.where(
      'articles.name ilike ? or ' \
      'ingredients.name ilike ? or ' \
      'suppliers.name ilike ?',
      "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%"
    )
  end
end

app/controllers/import/articles_controller.rb
module Import
  class ArticlesController < ApplicationController
    authorize_resource

    include ::CsvImportable
  end
end

app/views/articles/_boxes.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th>Kiste</th>
      <th class="text-end">Gesamtbedarf</th>
      <th class="text-end">Im Lager</th>
      <th class="text-end">bestellt</th>
      <th class="text-end">Bestellbedarf</th>
    </tr>
  </thead>

  <tbody>
    <% @article.boxes.each do |box| %>
      <tr>
        <td><%= link_to I18n.l(box.datetime), box %></td>
        <td class="text-end">
          <%= number_with_delimiter @article.sums_by_box.fetch(box.id, 0) %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @article.order_requirement_of(box).stock %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @article.order_requirement_of(box).ordered %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @article.order_requirement_of(box).quantity %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td class="text-end">
        <%= number_with_delimiter @article.group_box_articles.sum(:quantity) %>
      </td>
      <td class="text-end">
        <%= number_with_delimiter @article.article_box_order_requirements.sum(:stock) %>
      </td>
      <td class="text-end">
        <%= number_with_delimiter @article.article_box_order_requirements.sum(:ordered) %>
      </td>
      <td class="text-end">
        <%= number_with_delimiter @article.article_box_order_requirements.sum(:quantity) %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :ingredient, collection: Ingredient.order(:name) %>
    <%= f.association :supplier, collection: Supplier.order(:name) %>
    <%= f.input :nr %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :quantity %>
    <%= f.input :unit %>
    <%= f.input :notes %>
    <%= f.input :order_limit %>
    <%= f.input :priority %>
    <%= f.input :needs_cooling %>
    <%= f.input :packing_type, collection: Article.packing_types.keys.map { |key| [I18n.t("activerecord.enums.article.packing_type.#{key}"), key] }, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/_laga_row.html.erb
 <%= turbo_frame_tag dom_id(article), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
  <div class="d-flex w-100 justify-content-between">
    <div>
      <%= link_to "#{article.supplier} - #{ article.ingredient}", article, data: {turbo_frame: '_top'} %><br/>
      <small><%= article.ingredient.commodity_group %></small>
    </div>
    <div class="row">
      <div class="col text-end">
        <% if article_stock_action.status.present? %>
          <span class="text-<%= article_stock_action.status == :success ? 'success' : 'danger' %>">
            <%= article_stock_action.result %>
          </span>
        <% end %>
        <% if article.packing_type == 'bulk' %>
          <%= article.quantity_unit_stock.humanize %>
        <% else %>
          <%= number_with_delimiter article.stock %><br/>
          à <%= article.quantity_unit.humanize %>
        <% end %>
      </div>
      <%= simple_form_for article_stock_action, url: update_stock_article_path(article), html: { class: 'col' } do |f|%>
        <%= f.input :action, class: 'form-control text-end', label: false, placeholder: (article.packing_type == 'bulk' ? 'g' : '') %>
      <% end %>
    </div>
  </div>
  <% if article.name %><div class="mb-1"><%= article.name %></div><% end %>
<% end %>

app/views/articles/_orders.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th>Bestellung</th>
      <th>status</th>
      <th class="text-end">bestellt</th>
      <th class="text-end">geliefert</th>
    </tr>
  </thead>

  <tbody>
    <% @article.order_articles.includes(:order).order('orders.coverage').each do |order_article| %>
      <tr>
        <td><%= link_to I18n.l(order_article.order.coverage_begin), order_article.order %></td>
        <td><%= I18n.t("activerecord.enums.order.state.#{order_article.order.state}") %></td>
        <td class="text-end">
          <%= number_with_delimiter order_article.quantity_ordered %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter order_article.quantity_delivered %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_table.html.erb
<table id="articles-table" class="table table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <% unless defined?(ingredient) %><th>Warengruppe</th><th>Zutat</th><% end %>
      <% unless defined?(supplier) %><th>Lieferant</th><% end %>
      <% if defined?(ingredient) %><th>Prio</th><% end %>
      <th>Nr.</th>
      <th class="text-end">Lager</th>
      <th class="text-end">Überschuss</th>
      <% if defined?(show_price) %>
      <th class="text-end">Preis</th>
      <th class="text-end">Grundpreis</th>
      <% end %>
      <th class="text-end">max. Bestellmenge</th>
      <% if defined?(@order_counts) %><th>Bestellungen</th><% end %>
      <th>Notizen</th>
    </tr>
  </thead>

  <tbody>
    <% articles.each do |article| %>
      <tr>
        <td><%= link_to article %></td>
        <% unless defined?(ingredient) %>
          <td><%= article.ingredient.commodity_group %></td>
          <td><%= link_to article.ingredient, article.ingredient %></td>
        <% end %>
        <% unless defined?(supplier) %>
          <td><%= link_to article.supplier, article.supplier %></td>
        <% end %>
        <% if defined?(ingredient) %><td><%= article.priority %></td><% end %>
        <td><%= article.nr %></td>
        <td class="text-end"><%= number_with_delimiter article.stock %></td>
        <td class="text-end"><%= article.surplus %></td>
        <% if defined?(show_price) %>
        <td class="text-end"><%= number_with_delimiter article.price %> €</td>
        <td class="text-end"><%= number_with_precision(article.base_price, precision: 2) %> €/(kg/l/Stk)</td>
        <% end %>
        <td class="text-end"><%= number_with_delimiter article.order_limit %></td>
        <% if defined?(@order_counts) %><td><%= @order_counts.fetch(article.id, 0) %></td><% end %>
        <td><%= article.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/edit.html.erb
<h1>Artikel bearbeiten</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Inventurliste', inventory_list_articles_path(format: 'pdf'), class: 'btn btn-sm btn-secondary' %>
  <%= link_to 'Neuen Artikel anlegen', new_article_path, class: 'btn btn-sm btn-primary' %>
</div>

<%= render 'table', articles: @articles %>

app/views/articles/laga.html.erb
<%= form_with url: laga_articles_path, method: :get, data: { controller: "search-form", search_form_target: "form", turbo_frame: 'laga_list' } do |f| %>
  <div class="row">
    <div class="col">
      <div class="btn-group" data-bs-toggle="buttons">
        <label class="btn btn-secondary active">
          <input type="radio" class="btn-check" checked autocomplete="off" data-action="search-form#search" name="cooling" value="all">
          Alle
        </label>
        <label class="btn btn-danger">
          <input type="radio" class="btn-check" autocomplete="off" data-action="search-form#search" name="cooling" value="warm">
          Warm
        </label>
        <label class="btn btn-primary">
          <input type="radio" class="btn-check" autocomplete="off" data-action="search-form#search" name="cooling" value="cold">
          Kalt
        </label>
      </div>
    </div>
    <div class="col">
      <%= f.text_field :search, placeholder: "Suchen", autocomplete: "off", class: "form-control",
                       data: { action: "search-form#search" } %>
    </div>
  </div>
<% end %>

<%= turbo_frame_tag 'laga_list' do %>
  <div class="list-group">
    <% @articles.each do |article| %>
      <%= render 'laga_row', article: article, article_stock_action: ArticleStockAction.new(article: article) %>
    <% end %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>Neuen Artikel anlegen</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Löschen', @article, data: { turbo_method: :delete, turbo_confirm: 'Bist du sicher?' }, class: 'btn btn-danger' %>
  <%= link_to 'Bearbeiten', edit_article_path(@article), class: 'btn btn-primary' %>
  <%= link_to 'Zurück', articles_path, class: 'btn btn-light' %>
</div>

<h1><%= @article %></h1>

<p><%= link_to @article.ingredient %> von <%= link_to @article.supplier %></p>

<dl>
  <dt><%= link_to 'Lagerbestand', [@article, :stock_changes]%></dt>
  <dd>
    <%= number_with_delimiter @article.stock %>
    <small><%= @article.quantity_unit_stock.humanize %></small>
  </dd>
  <dt>Packstraßenbestand</dt>
  <dd>
    <%= number_with_delimiter @article.packing_lane_stock %>
    <small><%= @article.quantity_unit_packing_lane_stock.humanize %></small>
  </dd>
  <dt>Überschuss</dt>
  <dd>
    <%= number_with_delimiter @article.surplus %>
    <small><%= @article.quantity_unit_surplus.humanize %></small>
  </dd>
  <dt>Preis</dt>
  <dd><%= number_with_delimiter @article.price %> €</dd>
  <dt>Grundpreis</dt>
  <dd><%= number_with_precision(@article.base_price, precision: 2) %> €/(kg/l/Stk)</dd>
  <dt><%= Article.human_attribute_name("quantity") %> & <%= Article.human_attribute_name("packing_type") %></dt>
  <dd>
    <%= @article.quantity_unit.humanize %>
    <%= I18n.t("activerecord.enums.article.packing_type.#{@article.packing_type}") %>
  </dd>
  <dt>Kühlbedarf</dt>
  <dd><%= I18n.t @article.needs_cooling? %></dd>
  <dt>Notizen</dt>
  <dd><%= @article.notes %></dd>
  <dt>verbleibende mögliche Bestellmenge</dt>
  <dd>
    <%= number_with_delimiter @article.current_order_limit %>
    (<%= number_with_delimiter @article.order_limit %> anfangs;
    <%= number_with_delimiter @article.quantity_ordered %> bestellt;
    <%= number_with_delimiter @article.quantity_delivered %> geliefert)
  </dd>
</dl>

<%= render 'boxes' %>
<%= render 'orders' %>

<%= link_to 'Neuen Vorrat anlegen', new_article_hoard_path(@article), class: 'btn btn-sm btn-primary float-end' %>
<h3>Vorrat</h3>
<%= render partial:'hoards/table', locals: { hoards: @article.hoards } %>

app/views/articles/update_stock.html.erb
<%= render 'laga_row', article: @article, article_stock_action: @article_stock_action %>