config/routes.rb
Rails.application.routes.draw do
  resources :packing_lanes do
    resources :packing_lane_boxes, only: %i[show edit update], shallow: true do
      member do
        post 'create_stock'
        post 'move_diff_from_stock'
        post 'move_to_stock'
        get 'packing_list'
      end
    end
  end
  resources :participants do
    resources :group_changes, shallow: true, except: %i[index show]
  end
  resources :diets
  resources :orders do
    member do
      post 'order'
      post 'deliver'
      post 'store'
      post 'cancel'
    end
    resources :order_articles, only: %i[create destroy], shallow: true
    get 'edit_quantities', on: :member
  end
  resources :boxes do
    resources :group_boxes, path: 'groups', as: :group, only: [:show] do
      resources :extra_ingredients, only: %i[new create edit update destroy], shallow: true
      resources :group_box_ingredients, path: 'ingredients', as: :ingredient, only: [:show]
    end
    member do
      get 'packing_lists_groups'
      get 'packing_lists_articles'
      get 'ingredient_meals'
      get 'packing_lists_missing_ingredients'
      get 'packing_lists_lanes'
      get 'all_packing_lists'
    end
  end
  resources :groups do
    resources :group_meal_participations, shallow: true, except: :show, path: 'meal_participations'
    get 'meals_overview', on: :collection
    get 'diets_overview', on: :collection
    resources :meal_selections, only: %i[index create destroy], shallow: true
  end
  devise_for :users
  resources :suppliers
  resources :articles do
    resources :hoards, shallow: true, except: %i[index show]
    resources :stock_changes, only: %i[index]
    get :laga, on: :collection
    post :update_stock, on: :member
    get :inventory_list, on: :collection
  end
  root 'dashboards#show'
  resource :dashboard do
    get 'groups_missing_packing_lane'
    get 'ingredients_missing_article'
    get 'ingredients_without_box'
    get 'recipes_without_content'
    get 'missing_ingredients'
    get 'upcoming_boxes'
    get 'upcoming_order_requirements'
    get 'upcoming_orders'
  end
  resources :meals
  resources :ingredients do
    get 'all', on: :collection
    get 'with_missing_alternatives', on: :collection
    resources :ingredient_alternatives, shallow: true, except: %i[index show]
  end
  resources :recipes do
    get 'kochbuch', on: :collection
  end
  resources :calculations, only: :update
  namespace :import do
    root 'imports#show'
    resource :articles, only: :create
    resource :ingredients, only: :create
    resource :participants, only: :create
    resource :groups, only: :create
    resource :diets_ingredients, only: :create
    resource :extra_ingredients, only: :create
  end
  resources :users, except: :show
  resources :units, only: %i[index new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :packing_lane, optional: true

  has_many :group_meals
  has_many :group_boxes
  has_many :group_meal_participations, dependent: :destroy
  has_many :group_meal_participants
  has_many :participants, dependent: :restrict_with_error
  has_many :meal_selections, dependent: :destroy
  has_rich_text :notes

  validates :name, uniqueness: true, presence: true
  validates :internal_name, uniqueness: true, unless: ->(group) { group.internal_name.blank? }

  before_save do
    self.internal_name = nil if internal_name.blank?
  end

  def to_s
    display_name
  end

  def display_name
    if internal_name.nil?
      name
    else
      "#{internal_name} (#{name})"
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.order(name: :asc).includes(:packing_lane).all
    @servings =
      GroupMealParticipant
      .group(:group_id, :meal_id).count
      .group_by { |k, _v| k[0] }
      .transform_values { |vs| vs.map { |v| v[1] }.max }
  end

  def meals_overview
    @groups = Group.order(internal_name: :asc, name: :asc).all
    @meals =
      Meal
      .includes(:recipe)
      .order(datetime: :asc)
    @servings = GroupMealParticipant.group(:group_id, :meal_id).count
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def diets_overview
    @groups = Group.reorder(internal_name: :asc, name: :asc).all
    @diets = Diet.order(:name)
    @group_participants =
      GroupMealParticipant
      .distinct.pluck(:group_id, :participant_id)
      .group_by { |i| i[0] }.transform_values { |v| v.map { |i| i[1] } }
  end

  def show
    @group_meals = @group
                   .group_meals
                   .includes(meal: %i[recipe box])
                   .joins(:meal)
                   .order('meals.datetime': :asc)
    @servings = @group.group_meal_participants.group(:meal_id).count
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Kochgruppe wurde erfolgreich erstellt.' }
      else
        format.html { render :new, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Kochgruppe wurde erfolgreich aktualisiert.' }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @group.destroy
        format.html { redirect_to groups_url, notice: 'Kochgruppe wurde erfolgreich gelöscht.', status: :see_other }
      else
        format.html do
          redirect_to @group, status: :see_other, alert: @group.errors.full_messages
        end
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.expect(group: %i[name internal_name hunger_factor notes packing_lane_id
                            skip_mandatory_meals])
  end
end

app/controllers/import/groups_controller.rb
module Import
  class GroupsController < ApplicationController
    authorize_resource

    include ::CsvImportable
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :internal_name %>
    <%= f.input :hunger_factor %>
    <%= f.association :packing_lane %>
    <%= f.input :skip_mandatory_meals %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.rich_text_area :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/groups/diets_overview.html.erb
<h1>Kochgruppen - Ernährungsbesonderheiten</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>int. Name</th>
      <th>Ernährungsbesonderheiten</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.internal_name %></td>
        <td>
          <% data = DietParticipant.where(participant_id: @group_participants.fetch(group.id, [])).group(:diet_id).count %>
          <% @diets.select{ |d| data[d.id] }.each do |diet| %>
            <%= diet %>: <%= data[diet.id] %><br />
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<h1>Kochgruppe bearbeiten</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Besonderheitenübersicht', diets_overview_groups_path, class: 'btn btn-secondary' %>
  <%= link_to 'Mahlzeitenübersicht', meals_overview_groups_path, class: 'btn btn-secondary' %>
  <%= link_to 'Neue Kochgruppe', new_group_path, class: 'btn btn-primary' %>
</div>

<h1>Kochgruppen</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>int. Name</th>
      <th>max. Portionen</th>
      <th>Packstraße</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.internal_name %></td>
        <td><%= @servings.fetch(group.id, 0) %></td>
        <td>
          <% if group.packing_lane %>
            <%=link_to group.packing_lane, group.packing_lane %>
          <% else %>
            <span class="text-danger">Fehlt</span>
          <% end %>
          </td>
        <td><%= link_to 'Anzeigen', group %></td>
        <td><%= link_to 'Bearbeiten', edit_group_path(group) %></td>
        <td><%= link_to 'Löschen', group, data: { turbo_method: :delete, turbo_confirm: 'Bist du sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/meals_overview.csv.erb
Kochgruppe,<% @meals.each do |meal| %>"<%= meal.to_s.gsub('"', '""').html_safe %>",<% end %>
<% @groups.each do |group| %>
"<%= group.display_name.gsub('"', '""').html_safe %>",<% @meals.each do |meal| %><%= @servings.fetch([group.id, meal.id], nil) %>,<% end %>
<% end %>

app/views/groups/meals_overview.html.erb
<%= link_to 'CSV-Download', meals_overview_groups_path(format: :csv), class: 'btn btn-secondary float-end' %>

<h1>Mahlzeitenübersicht</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Kochgruppe</th>
      <% @meals.each do |meal| %>
      <th><%= meal %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.display_name %></td>
        <% @meals.each do |meal| %>
        <td><%= @servings.fetch([group.id, meal.id], nil) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>Neue Kochgruppe</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Mahlzeiten-Auswahl verwalten', group_meal_selections_path(@group), class: 'btn btn-default' %>
  <%= link_to 'manuelle Mahlzeit-Teilnahmen verwalten', group_group_meal_participations_path(@group), class: 'btn btn-default' %>
  <%= link_to 'Bearbeiten', edit_group_path(@group), class: 'btn btn-primary' %>
  <%= link_to 'Zurück', groups_path, class: 'btn btn-default' %>
</div>

<h1>
  Kochgruppe <%= @group.display_name %>
</h1>

<dl>
  <dt>Hunger-Faktor</dt>
  <dd><%= @group.hunger_factor %></dd>
  <dt>Packstraße</dt>
  <dd><%= @group.packing_lane %></dd>
  <% if feature(:lama) %>
  <dt>Lama uuid</dt>
  <dd><%= @group.lama_uuid %></dd>
  <% end %>
</dl>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Zeitpunkt</th>
      <th>Rezept</th>
      <th class="text-end">Portionen</th>
      <th>Kiste</th>
      <th>Ursprung</th>
    </tr>
  </thead>

  <tbody>
    <% day = nil %>
    <% @group_meals.each do |group_meal| %>
      <% meal = group_meal.meal %>
      <% if meal.datetime.to_date != day %>
        <% day = meal.datetime.to_date %>
        <tr><th colspan="<%= 5 %>"><%= l day, format: :weekday %></th></tr>
      <% end %>
      <tr>
        <td><%= l meal.datetime, format: :time_only %></td>
        <td><%= link_to meal.recipe, meal.recipe %></td>
        <td class="text-end"><%= @servings[meal.id] %></td>
        <td>
          <% if meal.box %>
            <%= link_to l(meal.box.datetime, format: :time_only), [meal.box, group_meal.group] %>
          <% else %>
            <span class="text-danger">Kiste unklar</span>
          <% end %>
        </td>
        <td><%= I18n.t("activerecord.enums.group_meal.origin.#{group_meal.origin}") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>Notizen</strong>
  <%= @group.notes %>
</p>