config/routes.rb
Rails.application.routes.draw do
  resources :packing_lanes do
    resources :packing_lane_boxes, only: %i[show edit update], shallow: true do
      member do
        post 'create_stock'
        post 'move_diff_from_stock'
        post 'move_to_stock'
        get 'packing_list'
      end
    end
  end
  resources :participants do
    resources :group_changes, shallow: true, except: %i[index show]
  end
  resources :diets
  resources :orders do
    member do
      post 'order'
      post 'deliver'
      post 'store'
      post 'cancel'
    end
    resources :order_articles, only: %i[create destroy], shallow: true
    get 'edit_quantities', on: :member
  end
  resources :boxes do
    resources :group_boxes, path: 'groups', as: :group, only: [:show] do
      resources :extra_ingredients, only: %i[new create edit update destroy], shallow: true
      resources :group_box_ingredients, path: 'ingredients', as: :ingredient, only: [:show]
    end
    member do
      get 'packing_lists_groups'
      get 'packing_lists_articles'
      get 'ingredient_meals'
      get 'packing_lists_missing_ingredients'
      get 'packing_lists_lanes'
      get 'all_packing_lists'
    end
  end
  resources :groups do
    resources :group_meal_participations, shallow: true, except: :show, path: 'meal_participations'
    get 'meals_overview', on: :collection
    get 'diets_overview', on: :collection
    resources :meal_selections, only: %i[index create destroy], shallow: true
  end
  devise_for :users
  resources :suppliers
  resources :articles do
    resources :hoards, shallow: true, except: %i[index show]
    resources :stock_changes, only: %i[index]
    get :laga, on: :collection
    post :update_stock, on: :member
    get :inventory_list, on: :collection
  end
  root 'dashboards#show'
  resource :dashboard do
    get 'groups_missing_packing_lane'
    get 'ingredients_missing_article'
    get 'ingredients_without_box'
    get 'recipes_without_content'
    get 'missing_ingredients'
    get 'upcoming_boxes'
    get 'upcoming_order_requirements'
    get 'upcoming_orders'
  end
  resources :meals
  resources :ingredients do
    get 'all', on: :collection
    get 'with_missing_alternatives', on: :collection
    resources :ingredient_alternatives, shallow: true, except: %i[index show]
  end
  resources :recipes do
    get 'kochbuch', on: :collection
  end
  resources :calculations, only: :update
  namespace :import do
    root 'imports#show'
    resource :articles, only: :create
    resource :ingredients, only: :create
    resource :participants, only: :create
    resource :groups, only: :create
    resource :diets_ingredients, only: :create
    resource :extra_ingredients, only: :create
  end
  resources :users, except: :show
  resources :units, only: %i[index new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/box.rb
class Box < ApplicationRecord
  enum :box_type, { default: 0, base_box: 1, fresh_box: 2 }
  enum :status, { stocked: 0, picked: 1, packed: 2 }

  has_many :box_meals
  has_many :meals, through: :box_meals
  has_many :group_box_ingredient_unit_caches
  has_many :ingredients, -> { distinct }, through: :group_box_ingredient_unit_caches
  has_many :groups, -> { distinct }, through: :group_box_ingredient_unit_caches
  has_many :extra_ingredients, dependent: :destroy
  has_many :missing_ingredients
  has_many :group_box_articles
  has_many :articles, -> { distinct }, through: :group_box_articles
  has_many :article_box_order_requirements
  has_rich_text :groups_info

  default_scope { order(datetime: :asc) }

  def to_s
    "Kiste am #{I18n.l datetime}"
  end

  def unit_sums
    @unit_sums =
      group_box_ingredient_unit_caches
      .group(:ingredient_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| a.map { |b| QuantityUnit.new(b[1], b[0][1]) } }
  end

  def missing_ingredient_sums_by_ingredient
    @missing_ingredient_sums_by_ingredient =
      missing_ingredients
      .group(:ingredient_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| a.map { |b| QuantityUnit.new(b[1], b[0][1]) } }
  end

  def sums_by_article
    @sums_by_article ||= group_box_articles.group(:article_id).sum(:quantity)
  end

  def order_requirements
    @order_requirements ||= article_box_order_requirements.index_by { |abor| abor.article_id }
  end

  def order_requirement_of(article)
    order_requirements.fetch(article.id, NoOrderRequirement.new)
  end

  def needs_order?
    article_box_order_requirements.where.not(quantity: 0).exists?
  end

  def awaiting_delivery?
    article_box_order_requirements.where.not(ordered: 0).exists?
  end

  def packing_lane_boxes
    PackingLane.order(:name).map do |packing_lane|
      PackingLaneBox.new(packing_lane:, box: self)
    end
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  authorize_resource
  before_action \
    :set_box,
    only: %i[
      show edit update destroy
      packing_lists_articles
      packing_lists_groups
      packing_lists_missing_ingredients
      ingredient_meals
      packing_lists_lanes
      all_packing_lists
    ]

  def index
    @boxes = Box.all
  end

  def show; end

  def ingredient_meals
    @ingredient_meals =
      MealIngredientBox
      .where(box: @box)
      .includes(meal: :recipe)
      .group_by(&:ingredient_id)
      .transform_values do |mibs|
        mibs.map(&:meal)
      end
  end

  def new
    @box = Box.new
  end

  def edit; end

  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Kiste wurde erfolgreich erstellt.' }
      else
        format.html { render :new, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Kiste wurde erfolgreich aktualisiert.' }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @box.destroy
        format.html { redirect_to boxes_url, notice: 'Kiste wurde erfolgreich gelöscht.', status: :see_other }
      else
        format.html do
          redirect_to @box, status: :see_other, alert: @box.errors.full_messages
        end
      end
    end
  end

  def packing_lists_groups
    render_packing_pdf PackingListsGroups.new(@box)
  end

  def packing_lists_articles
    render_packing_pdf PackingListsArticles.new(@box, filter: filter_param)
  end

  def packing_lists_missing_ingredients
    render_packing_pdf PackingListsMissingIngredients.new(@box)
  end

  def packing_lists_lanes
    render_packing_pdf PackingListsLanes.new(@box)
  end

  def all_packing_lists
    render_packing_pdf AllBoxLists.new(@box)
  end

  private

  def render_packing_pdf(pdf)
    if ArticlePackingPlanner.fresh?
      render_pdf pdf
    else
      redirect_back fallback_location: root_path, alert: 'Packplanung muss neu berechnet werden'
    end
  end

  def filter_param
    case params['filter']
    when 'warm' then :warm
    when 'cold' then :cold
    end
  end

  def set_box
    @box = Box.find(params[:id])
  end

  def box_params
    params.expect(box: %i[datetime box_type status groups_info])
  end
end

app/views/boxes/_articles.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th>Artikel</th>
      <th class="text-end">Gesamtbedarf</th>
      <th class="text-end">Im Lager</th>
      <th class="text-end">bestellt</th>
      <th class="text-end">Bestellbedarf</th>
    </tr>
  </thead>

  <tbody>
    <% @box.articles.joins(:ingredient).reorder('ingredients.name': :asc).select('articles.*, ingredients.name AS ingredient_name').each do |article| %>
      <tr>
        <td><%= link_to article.full_name, article %></td>
        <td class="text-end">
          <%= number_with_delimiter @box.sums_by_article.fetch(article.id, 0) %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @box.order_requirement_of(article).stock %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @box.order_requirement_of(article).ordered %>
        </td>
        <td class="text-end">
          <%= number_with_delimiter @box.order_requirement_of(article).quantity %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boxes/_form.html.erb
<%= simple_form_for(@box) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :datetime %>
    <%= f.input :box_type, collection: Box.box_types.keys.map { |key| [I18n.t("activerecord.enums.box.box_type.#{key}"), key] }, include_blank: false %>
    <%= f.input :status, collection: Box.statuses.keys.map { |key| [I18n.t("activerecord.enums.box.status.#{key}"), key] }, include_blank: false %>
  </div>

  <div class="field">
    <%= f.label :groups_info %>
    <%= f.rich_text_area :groups_info %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/boxes/_groups.html.erb
<table class="table table-sm">
  <tr>
    <th>Gruppe</th>
  </tr>
  <% @box.groups.order(:name).each do |group| %>
    <tr>
      <td><%= link_to group.display_name, [@box, group] %></td>
    </tr>
  <% end %>
</table>

app/views/boxes/_ingredients.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th>Zutat</th>
      <th class="text-end">Bedarf</th>
      <th class="text-end">Fehlmenge</th>
      <% if defined?(show_meals) %><th>Mahlzeiten</th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @box.ingredients.order(:name).each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient, ingredient %></td>
        <td class="text-end"><%= @box.unit_sums[ingredient.id].map(&:humanize).join(', ') %></td>
        <td class="text-end">
          <%= @box.missing_ingredient_sums_by_ingredient.fetch(ingredient.id, []).map(&:humanize).join(', ') %>
        </td>
        <% if defined?(show_meals) %>
        <td>
          <ul>
          <% @ingredient_meals.fetch(ingredient.id, []).each do |meal| %>
            <li><%= link_to meal.recipe, meal %></li>
          <% end %>
          <ul>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boxes/_meals.html.erb
<table class="table table-sm">
  <tr>
    <th>Gericht</th>
    <th>Zeit</th>
  </tr>
  <% @box.meals.includes(:recipe).each do |meal| %>
    <tr>
      <td><%= link_to meal.recipe.name, meal.recipe %></td>
      <td><%= link_to l(meal.datetime), meal %></td>
    </tr>
  <% end %>
</table>

app/views/boxes/edit.html.erb
<h1>Kiste bearbeiten</h1>

<%= render 'form', box: @box %>

app/views/boxes/index.html.erb
<h1>Kisten</h1>

<%= link_to 'Neue Kiste', new_box_path, class: 'btn btn-primary btn-sm float-end' %>
<table class="table table-sm">
  <thead>
    <tr>
      <th>Zeitpunkt</th>
      <th>Typ</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= link_to l(box.datetime), box %></td>
        <td><%= I18n.t "activerecord.enums.box.box_type.#{box.box_type}" %></td>
        <td><%= I18n.t "activerecord.enums.box.status.#{box.status}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boxes/ingredient_meals.html.erb
<%= turbo_frame_tag 'ingredient_meals' do %>
<%= render 'ingredients', show_meals: true %>
<% end %>

app/views/boxes/new.html.erb
<h1>Neue Kiste</h1>

<%= render 'form', box: @box %>

app/views/boxes/show.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Löschen', @box, data: { turbo_method: :delete, turbo_confirm: 'Bist du sicher?' }, class: 'btn btn-danger' %>
  <%= link_to 'Bearbeiten', edit_box_path(@box), class: 'btn btn-primary' %>
  <%= link_to 'Zurück', boxes_path, class: 'btn btn-light' %>
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="printMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Drucken
  </a>

  <div class="dropdown-menu" aria-labelledby="printMenu">
    <%= link_to 'Packlisten pro Gruppe', [:packing_lists_groups, @box, format: :pdf], class: 'dropdown-item' %>
    <%= link_to 'Packlisten pro Artikel warm', [:packing_lists_articles, @box, format: :pdf, filter: :warm], class: 'dropdown-item' %>
    <%= link_to 'Packlisten pro Artikel kalt', [:packing_lists_articles, @box, format: :pdf, filter: :cold], class: 'dropdown-item' %>
    <%= link_to 'Packlisten Fehlmengen', [:packing_lists_missing_ingredients, @box, format: :pdf], class: 'dropdown-item' %>
    <%= link_to 'Alle Packlisten', [:all_packing_lists, @box, format: :pdf], class: 'dropdown-item' %>
  </div>
</div>
<h1>
  Kiste am <%= l @box.datetime %>
</h1>

<dl>
  <dt>Typ</dt>
  <dd><%= I18n.t("activerecord.enums.box.box_type.#{@box.box_type}") %></dd>
  <dt>Status</dt>
  <dd>
    <%= I18n.t("activerecord.enums.box.status.#{@box.status}") %>
    <% if @box.picked? %>
      <% @box.packing_lane_boxes.each do |packing_lane_box| %>
        <%= link_to packing_lane_box.packing_lane,
                    packing_lane_box,
                    class: "badge bg-#{packing_lane_box_status_color(packing_lane_box)}" %>
      <% end %>
    <% end %>
  </dd>
</dl>

<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-bs-toggle="tab" href="#articles" role="tab">Artikel</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#meals" role="tab">Mahlzeiten</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#ingredients" role="tab">Zutaten</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#groups" role="tab">Kochgruppen</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#info" role="tab">Info-Text</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#ingredient_meals" role="tab">Zutaten mit Mahlzeiten</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade show active" id="articles" role="tabpanel">
    <%= render 'articles' %>
  </div>
  <div class="tab-pane fade" id="meals" role="tabpanel">
    <%= render 'meals' %>
  </div>
  <div class="tab-pane fade" id="ingredients" role="tabpanel">
    <%= render 'ingredients' %>
  </div>
  <div class="tab-pane fade" id="groups" role="tabpanel">
    <%= render 'groups' %>
  </div>
  <div class="tab-pane fade" id="info" role="tabpanel">
    <p>
      <strong>Info-Text für Kochgruppen</strong>
      <%= @box.groups_info %>
    </p>
  </div>
  <div class="tab-pane fade" id="ingredient_meals" role="tabpanel">
    <%= turbo_frame_tag 'ingredient_meals', src: ingredient_meals_box_path(@box), target: '_top', loading: :lazy do %>Lade…<% end %>
  </div>
</div>