config/routes.rb
Rails.application.routes.draw do
  resources :packing_lanes do
    resources :packing_lane_boxes, only: %i[show edit update], shallow: true do
      member do
        post 'create_stock'
        post 'move_diff_from_stock'
        post 'move_to_stock'
        get 'packing_list'
      end
    end
  end
  resources :participants do
    resources :group_changes, shallow: true, except: %i[index show]
  end
  resources :diets
  resources :orders do
    member do
      post 'order'
      post 'deliver'
      post 'store'
      post 'cancel'
    end
    resources :order_articles, only: %i[create destroy], shallow: true
    get 'edit_quantities', on: :member
  end
  resources :boxes do
    resources :group_boxes, path: 'groups', as: :group, only: [:show] do
      resources :extra_ingredients, only: %i[new create edit update destroy], shallow: true
      resources :group_box_ingredients, path: 'ingredients', as: :ingredient, only: [:show]
    end
    member do
      get 'packing_lists_groups'
      get 'packing_lists_articles'
      get 'ingredient_meals'
      get 'packing_lists_missing_ingredients'
      get 'packing_lists_lanes'
      get 'all_packing_lists'
    end
  end
  resources :groups do
    resources :group_meal_participations, shallow: true, except: :show, path: 'meal_participations'
    get 'meals_overview', on: :collection
    get 'diets_overview', on: :collection
    resources :meal_selections, only: %i[index create destroy], shallow: true
  end
  devise_for :users
  resources :suppliers
  resources :articles do
    resources :hoards, shallow: true, except: %i[index show]
    resources :stock_changes, only: %i[index]
    get :laga, on: :collection
    post :update_stock, on: :member
    get :inventory_list, on: :collection
  end
  root 'dashboards#show'
  resource :dashboard do
    get 'groups_missing_packing_lane'
    get 'ingredients_missing_article'
    get 'ingredients_without_box'
    get 'recipes_without_content'
    get 'missing_ingredients'
    get 'upcoming_boxes'
    get 'upcoming_order_requirements'
    get 'upcoming_orders'
  end
  resources :meals
  resources :ingredients do
    get 'all', on: :collection
    get 'with_missing_alternatives', on: :collection
    resources :ingredient_alternatives, shallow: true, except: %i[index show]
  end
  resources :recipes do
    get 'kochbuch', on: :collection
  end
  resources :calculations, only: :update
  namespace :import do
    root 'imports#show'
    resource :articles, only: :create
    resource :ingredients, only: :create
    resource :participants, only: :create
    resource :groups, only: :create
    resource :diets_ingredients, only: :create
    resource :extra_ingredients, only: :create
  end
  resources :users, except: :show
  resources :units, only: %i[index new create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  enum :box_type, { default: 0, base_box: 1, fresh_box: 2 }

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
  has_many :ingredient_weights, dependent: :delete_all
  has_many :articles, dependent: :destroy
  has_many :suppliers, -> { distinc }, through: :articles
  has_many :extra_ingredients
  has_many :ingredient_alternatives, dependent: :destroy
  has_many :ingredient_substitutions, class_name: 'IngredientAlternative', foreign_key: :alternative_id,
                                      dependent: :restrict_with_error
  has_and_belongs_to_many :diets
  has_many :group_box_ingredient_unit_caches
  has_many :boxes, -> { distinct }, through: :group_box_ingredient_unit_caches
  has_many :missing_ingredients

  scope :in_meal_or_extra, lambda {
    left_outer_joins(:extra_ingredients, recipes: :meals)
      .where('("extra_ingredients"."id" IS NOT NULL OR "meals"."id" IS NOT NULL)').distinct
  }

  validates :name, presence: true
  validates :box_type, presence: true
  validates :uses_hunger_factor, inclusion: { in: [true, false] }

  after_save :persist_diet_names

  def in_meals
    Meal
      .joins(recipe: :recipe_ingredients)
      .where(recipe: { recipe_ingredients: { ingredient_id: id } })
      .joins('LEFT OUTER JOIN ingredient_weights ON ' \
             'ingredient_weights.ingredient_id = recipe_ingredients.ingredient_id AND ' \
             'ingredient_weights.unit = recipe_ingredients.unit')
      .select(
        'meals.*',
        'recipe.name', 'recipe.servings AS recipe_servings',
        'recipe_ingredients.quantity', 'recipe_ingredients.unit',
        '(select array_agg(diet_id) from positive_diet_ingredients where recipe_ingredient_id = recipe_ingredients.id) as positive_diet_ids',
        'ingredient_weights.weight'
      ).order(datetime: :asc)
  end

  def to_s
    name
  end

  def unit_sums
    @unit_sums ||= QuantityUnits.new(
      group_box_ingredient_unit_caches
      .group(:unit).sum(:quantity)
      .map { |a| QuantityUnit.new(a[1], a[0]) }
    )
  end

  def unit_sums_by_box
    @unit_sums_by_box =
      group_box_ingredient_unit_caches
      .group(:box_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| QuantityUnits.new(a.map { |b| QuantityUnit.new(b[1], b[0][1]) }) }
  end

  def missing_ingredient_sums
    @missing_ingredient_sums ||= QuantityUnits.new(
      missing_ingredients
      .group(:unit).sum(:quantity)
      .map { |a| QuantityUnit.new(a[1], a[0]) }
    )
  end

  def missing_ingredient_sums_by_box
    @missing_ingredient_sums_by_box =
      missing_ingredients
      .group(:box_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| QuantityUnits.new(a.map { |b| QuantityUnit.new(b[1], b[0][1]) }) }
  end

  def order_requirements
    @order_requirements =
      ArticleBoxOrderRequirement
      .joins(:article).includes(:article)
      .merge(Article.unscope(:order).where(ingredient_id: id))
      .group_by(&:box_id).map do |box_id, order_requirements|
        [box_id, OrderRequirement.new(
          box_id:,
          quantity: QuantityUnit.sum(order_requirements.map(&:quantity_unit)),
          stock: QuantityUnit.sum(order_requirements.map(&:stock_quantity_unit)),
          ordered: QuantityUnit.sum(order_requirements.map(&:ordered_quantity_unit))
        )]
      end.to_h
  end

  def order_requirement_of(box)
    order_requirements.fetch(box.id, NoOrderRequirement.new(value: QuantityUnits.new))
  end

  attr_writer :diet_names

  def diet_names
    @diet_names ||= diets.pluck(:name)
  end

  private

  def persist_diet_names
    return if @diet_names.nil?

    self.diet_ids = Diet.where(name: diet_names).pluck(:id)
  end
end

app/controllers/import/ingredients_controller.rb
module Import
  class IngredientsController < ApplicationController
    authorize_resource

    include ::CsvImportable
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  authorize_resource
  before_action :set_ingredient, only: %i[show edit update destroy]

  def index
    @ingredients =
      Ingredient.where(no_buy: false).order(commodity_group: :asc, name: :asc)
    load_ingredient_sums
  end

  def all
    @ingredients = Ingredient.all.order(commodity_group: :asc, name: :asc)
    load_ingredient_sums
    render :index
  end

  def with_missing_alternatives
    @ingredients = GroupMealParticipantRecipeIngredientSubstCalculation
                   .where(final_ingredient_id: nil)
                   .includes(:group, recipe_ingredient: :ingredient, participant: :diets, meal: :recipe)
                   .group_by(&:ingredient)
  end

  def show; end

  def new
    @ingredient = Ingredient.new
  end

  def edit; end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Zutat wurde erfolgreich erstellt.' }
      else
        format.html { render :new, status: :unprocessable_content }
      end
    end
  end

  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Zutat wurde erfolgreich aktualisiert.' }
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @ingredient.destroy
        format.html { redirect_to ingredients_url, notice: 'Zutat wurde erfolgreich gelöscht.', status: :see_other }
      else
        format.html do
          redirect_to @ingredient, status: :see_other, alert: @ingredient.errors.full_messages
        end
      end
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.expect(ingredient: [:name, :commodity_group, :box_type, :uses_hunger_factor, :on_demand,
                               { diet_ids: [] }])
  end

  def load_ingredient_sums
    @unit_sums =
      GroupBoxIngredientUnitCache
      .group(:ingredient_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| a.map { |b| QuantityUnit.new(b[1], b[0][1]) } }
    @missing_sums =
      MissingIngredient
      .group(:ingredient_id, :unit).sum(:quantity)
      .group_by { |k, _v| k[0] }
      .transform_values { |a| a.map { |b| QuantityUnit.new(b[1], b[0][1]) } }
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def estimated_need_per_meal(ingredient)
    ingredient
      .in_meals.map do |meal_ingredient|
      if meal_ingredient.recipe_servings
        factor = meal_ingredient.needed_servings(
          meal_ingredient.positive_diet_ids || []
        ) / meal_ingredient.recipe_servings
        {
          quantity_unit: QuantityUnit.new(
            meal_ingredient.quantity * factor,
            meal_ingredient.unit
          ),
          meal: meal_ingredient,
          weight: meal_ingredient.weight
        }
      else
        {
          meal: meal_ingredient,
          quantity_unit: QuantityUnit.new(1, 'Faktor unklar')
        }
      end
    end.group_by do |need|
      [need[:meal].id, need[:quantity_unit].unit]
    end
    .map do |meal_unit, needs|
      raise unless needs.all? { |need| need[:weight] == needs[0][:weight] }

      {
        meal: needs[0][:meal],
        weight: needs[0][:weight],
        quantity_unit: QuantityUnit.new(
          needs.map { |need| need[:quantity_unit].quantity }.sum,
          meal_unit[1]
        )
      }
    end
  end

  def estimated_need_total(ingredient)
    QuantityUnit.sum(
      estimated_need_per_meal(ingredient)
        .map { |need| estimate_weight(need) }
    )
  end

  def estimate_weight(need)
    return need[:quantity_unit] if need[:quantity_unit].unit == 'g' || !need[:weight]

    QuantityUnit.new(need[:quantity_unit].quantity * need[:weight], 'g')
  end

  def missing_alternatives_stats(ingredient_problems)
    ingredient_problems.group_by(&:diet_string).map do |diet, diet_problems|
      participants = diet_problems.map(&:participant).uniq
      groups = diet_problems.map(&:group).uniq
      meals = diet_problems.map(&:meal).uniq
      [
        diet, {
          participants: participants,
          groups: groups,
          meals: meals
        }
      ]
    end.to_h
  end

  def problems_count_color(count)
    case count
    when ..1 then 'success'
    when ..5 then 'warning'
    else 'danger'
    end
  end
end

app/views/ingredients/_form.html.erb
<%= simple_form_for(ingredient) do |f| %>
  <%= f.input :name %>
  <%= f.input :commodity_group %>
  <%= f.input :box_type, collection: Ingredient.box_types.keys.map { |key| [I18n.t("activerecord.enums.ingredient.box_type.#{key}"), key] }, include_blank: false %>
  <%= f.input :uses_hunger_factor %>
  <%= f.input :on_demand %>
  <%= f.association :diets, collection: Diet.order(:name), input_html: { class: 'select2' } %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/ingredients/_problem_details.html.erb
<td class="text-end">
  <%= link_to stats.count, "##{link_id}", data: { 'bs-toggle': 'collapse' }, class: "badge bg-#{problems_count_color(stats.count)}" %>
  <%= content_tag :div, class: 'collapse text-left', id: link_id do %>
    <ul>
      <% stats.take(5).each do |problem| %>
      <li><%= link_to problem, problem %></li>
      <% end %>
      <%= content_tag('li', '…') if stats.count > 5 %>
    </ul>
  <% end %>
</td>

app/views/ingredients/edit.html.erb
<h1>Zutat bearbeiten</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Neue Zutat anlegen', new_ingredient_path, class: 'btn btn-primary btn-sm' %>
  <%= link_to 'fehlende Alternativen', with_missing_alternatives_ingredients_path, class: 'btn btn-sm btn-warning' %>
</div>

<h1>Zutaten</h1>

<table id="ingredients-table" class="table table-sm">
  <thead>
    <tr>
      <th>Warengruppe</th>
      <th>Name</th>
      <% if feature(:estimation) %>
      <th class="text-end">geschätzter Bedarf</th>
      <% end %>
      <th class="text-end">tatsächlicher Bedarf</th>
      <th class="text-end">Artikel</th>
      <th class="text-end">Fehlmenge</th>
      <th>Kiste</th>
      <th>HUF</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <% estimation = estimated_need_total(ingredient) if feature(:estimation) %>
      <tr>
        <td><%= ingredient.commodity_group %></td>
        <td><%= link_to ingredient.name, ingredient %></td>
        <% if feature(:estimation) %>
        <td class="text-end">
          <% estimation.each do |need| %>
            <%= humanize_unit(need[:quantity], need[:unit]) %>
          <% end %>
        </td>
        <% end %>
        <td class="text-end">
          <%= @unit_sums.fetch(ingredient.id, []).map(&:humanize).join(', ') %>
        </td>
        <td class="text-end"><%= ingredient.articles.count %></td>
        <td class="text-end"><%= @missing_sums.fetch(ingredient.id, []).map(&:humanize).join(', ') %></td>
        <td><%= I18n.t "activerecord.enums.ingredient.box_type.#{ingredient.box_type}" %></td>
        <td><%= ingredient.uses_hunger_factor? ? 'j' : 'n' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/new.html.erb
<h1>Neue Zutat</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<div class="btn-group float-end" role="group">
  <%= link_to 'Löschen', @ingredient, data: { turbo_method: :delete, turbo_confirm: 'Bist du sicher?' }, class: 'btn btn-danger' %>
  <%= link_to 'Bearbeiten', edit_ingredient_path(@ingredient), class: 'btn btn-primary' %>
  <%= link_to 'Zurück', ingredients_path, class: 'btn btn-light' %>
</div>

<h1><%= @ingredient.name %> <small><%= @ingredient.commodity_group %></small></h1>

<dl>
   <% if feature(:estimation) %>
  <dt>geschätzter Bedarf</dt>
  <dd>
    <% estimated_need_total(@ingredient).each do |quantity_unit| %>
      <%= quantity_unit.humanize %>
    <% end %>
  </dd>
  <% end %>
  <dt>tatsächlicher Bedarf</dt>
  <dd>
    <% @ingredient.unit_sums.each do |unit_sum| %>
      <%= unit_sum.humanize %>
    <% end %>
  </dd>
  <dt>Fehlmenge</dt>
  <dd>
    <% @ingredient.missing_ingredient_sums.each do |unit_sum| %>
      <%= unit_sum.humanize %>
    <% end %>
  </dd>
  <dt>Eigenschaften</dt>
  <dd>
    <span class="badge bg-primary rounded-pill">
      Kiste: <%= I18n.t("activerecord.enums.ingredient.box_type.#{@ingredient.box_type}") %>
    </span>
    <% if @ingredient.uses_hunger_factor? %>
    <span class="badge bg-success rounded-pill">
      Hunger-Faktor aktiv
    </span>
    <% end %>
    <% if @ingredient.on_demand? %>
    <span class="badge bg-warning rounded-pill">
      Nur auf Nachfrage
    </span>
    <% end %>
  </dd>
</dl>

<h2>problematische Ernährungsweisen</h2>
<ul>
  <% @ingredient.diets.order(:name).each do |diet| %>
    <li>
      <%= link_to diet, diet %>
    </li>
  <% end %>
</ul>

<%= link_to 'Neue Alternative anlegen', new_ingredient_ingredient_alternative_path(@ingredient), class: 'btn btn-primary btn-sm float-end' %>
<%= render 'ingredient_alternatives/table', ingredient_alternatives: @ingredient.ingredient_alternatives %>

<h2>Gewicht</h2>
<ul class="list-group">
  <% @ingredient.ingredient_weights.each do |ingredient_weight| %>
    <li class="list-group-item">
      <%= ingredient_weight.quantity_unit_base.humanize %> umrechnen in <%= ingredient_weight.quantity_unit_weight.humanize %>
    </li>
  <% end %>
</ul>

<h2>Lieferanten</h2>

<%= link_to 'Neuen Artikel anlegen', new_article_path(ingredient_id: @ingredient), class: 'btn btn-sm btn-primary float-end' %>
<%= render 'articles/table', articles: @ingredient.articles, ingredient: true, show_price: true %>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Kiste</th>
      <th class="text-end">Bedarf</th>
      <th class="text-end">Im Lager</th>
      <th class="text-end">bestellt</th>
      <th class="text-end">Bestellbedarf</th>
      <th class="text-end">Fehlmenge</th>
      <th class="text-end">Überpackt</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredient.boxes.each do |box| %>
      <tr>
        <td><%= link_to I18n.l(box.datetime), box %></td>
        <td class="text-end">
          <%= humanize_units @ingredient.unit_sums_by_box[box.id] %>
        </td>
        <td class="text-end">
          <%= humanize_units @ingredient.order_requirement_of(box).stock %>
        </td>
        <td class="text-end">
          <%= humanize_units @ingredient.order_requirement_of(box).ordered %>
        </td>
        <td class="text-end">
          <%= humanize_units @ingredient.order_requirement_of(box).quantity %>
        </td>
        <td class="text-end">
          <%= humanize_units @ingredient.missing_ingredient_sums_by_box.fetch(box.id, QuantityUnits.new) %>
        </td>
        <td class="text-end">
          <%= (@ingredient.order_requirement_of(box).total.sum + @ingredient.missing_ingredient_sums_by_box.fetch(box.id, QuantityUnits.new) - @ingredient.unit_sums_by_box[box.id]).humanize  %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td class="text-end">
        <% @ingredient.unit_sums.each do |unit_sum| %>
          <%= unit_sum.humanize %>
        <% end %>
      </td>
      <td class="text-end">
        <%= humanize_units_sum @ingredient.order_requirements.values.map(&:stock).flatten %>
      </td>
      <td class="text-end">
        <%= humanize_units_sum @ingredient.order_requirements.values.map(&:ordered).flatten %>
      </td>
      <td class="text-end">
        <%= humanize_units_sum @ingredient.order_requirements.values.map(&:quantity).flatten %>
      </td>
      <td class="text-end">
        <% @ingredient.missing_ingredient_sums.each do |unit_sum| %>
          <%= unit_sum.humanize %>
        <% end %>
      </td>
      <td class="text-end">
        <%= (QuantityUnits.new(@ingredient.order_requirements.values.map(&:total).flatten) + @ingredient.missing_ingredient_sums - @ingredient.unit_sums).humanize %>
      </td>
    </tr>
  </tfoot>
</table>

<h2>Rezepte</h2>
<ul>
  <% @ingredient.recipes.each do |recipe| %>
    <li><%= link_to recipe, recipe %></li>
  <% end %>
</ul>

<% if feature(:estimation) %>
<h2>geschätzt in Mahlzeiten</h2>
<ul>
  <% estimated_need_per_meal(@ingredient).each do |need| %>
    <li>
      <%= l need[:meal].datetime, format: '%d.%m. %H:%M' %> <%= link_to need[:meal].name, need[:meal] %>
      <%= need[:quantity_unit].humanize %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/ingredients/with_missing_alternatives.html.erb
<h1>Zutaten mit fehlenden Alternativen</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Warengruppe</th>
      <th>Name</th>
      <th>Probleme bei</th>
      <th class="text-end">Kochgruppen</th>
      <th class="text-end">Teilnehmende</th>
      <th class="text-end">Mahlzeiten</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient, problems| %>
      <% ingredient_stats = missing_alternatives_stats(problems) %>
      <tr>
        <td rowspan="<%= ingredient_stats.size %>"><%= ingredient.commodity_group %></td>
        <td rowspan="<%= ingredient_stats.size %>"><%= link_to ingredient.name, ingredient %></td>
        <% ingredient_stats.each_with_index do |(diets, diet_stats), index| %>
          <% if index != 0 %>
      </tr>
      <tr>
          <% end %>
        <td><%= diets %></td>
        <%= render 'problem_details', stats: diet_stats[:groups], link_id: "collapse_ingredient_#{ingredient.id}_#{diets}" %>
        <%= render 'problem_details', stats: diet_stats[:participants], link_id: "collapse_ingredient_#{ingredient.id}_#{diets}" %>
        <%= render 'problem_details', stats: diet_stats[:meals], link_id: "collapse_ingredient_#{ingredient.id}_#{diets}" %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>